### ISSUE TITLE
Include Frontend in Dockerimage

### ISSUE THREAD

**Issue by schenklklopfer** [Studio-Link/mix#45]
**Is your feature request related to a problem? Please describe.**
Runtime and config for frontend isn't included in Docker Image

**Describe the solution you'd like**
When I start the Docker Image I want the frontend to start as well as the backend.
I cannot use anything without having a frontend.

**Describe alternatives you've considered**
As described in [README](https://github.com/Studio-Link/mix/blob/main/README.md#development), how to start frontend does not work.
```
[root@dcf04c93d633 webui]# npm install
bash: npm: command not found
```

**Additional context**
The frontend is compiled in the Dockerfile [HERE](https://github.com/Studio-Link/mix/blob/main/Dockerfile#L7).
But there is no nodejs and no nginx installed in the "Final image" - as it is described in your documentation [HERE](https://mix.studio.link/self-hosting/install-source-ubuntu24_04).
So of course if I try to connect to the running Service on port 9999 (which is the backend) I only get: mix: no Session-ID header.

**Comment by sreimers** [comment]
Docker support is work in progress, I just added a new PR https://github.com/Studio-Link/mix/pull/46 with some improvements.
